### ISSUE TITLE
[COMMON] 이용 중인 사물함 상태 예약 변경 기능 추가

### ISSUE THREAD

**Issue by YESHYUNGSEOK** [innovationacademy-kr/Cabi#1395]
### 작업 설명

관리자 페이지에서 이미 사용 되고 있는 사물함의 상태(개인, 공유, 동아리)를 예약 변경할 수 있는 기능을 추가합니다.

### 접근 방법

- FE
- 기존의 상태 관리 모달에 예약 변경에 대한 드롭다운을 추가합니다.
- 기존에 사물함 상태 변경 api를 수정하여 예약 변경 상태 또한 업데이트해 줍니다.

- BE
- 기존의 사물함에 대한 렌트 타입 변경 api에 예약 변경 기능을 추가합니다.

**Comment by Ssuamje** [comment]
<img width="459" alt="image" src="https://github.com/innovationacademy-kr/42cabi/assets/105692206/aa2829e5-4c4a-4268-87dc-f3e0f2eabf9d">
