### ISSUE TITLE
[COMMON] 수요지식회 폴더 구조 분리 #1559

### ISSUE THREAD

**Issue by junyoung2015** [innovationacademy-kr/Cabi#1563]
### 작업 설명

- 프론트엔드의 `frontend/src` 폴더 내 Cabinet 과 Presentation 으로 관련 컴포넌트를 분리해서 관리하려고 합니다.

### 접근 방법

- 폴더를 분리함에 따라 수요지식회 전용 Layout 및 asset, component, pages, constants 등이 생길 예정입니다.

**Comment by sichoi42** [comment]
패키지 구조를 변경한다면 배포 스크립트의 수정도 필요할 것 같네요..! github acions 워크플로우 코드, package.json 스크립트 등
