### ISSUE TITLE
[FE]  어드민 슬랙 알림 기능 추가

### ISSUE THREAD

**Issue by jimchoi9** [innovationacademy-kr/Cabi#1581]
### 작업 설명

<img width="709" alt="image" src="https://github.com/innovationacademy-kr/Cabi/assets/146968639/a6e8b20d-ee4f-42f6-a7d4-f0f7300a5460">
어드민에서 슬랙 알림을 보낼 수 있고, 각각 템플릿을 선택해 전송하는 기능을 추가합니다

### 접근 방법

피그마 참고해서 기능 추가하겠습니다.

**Comment by sichoi42** [comment]
가능한지는 잘 모르겠지만 메시지 내용이 슬랙에서 실제로 어떻게 보이게 될지 preview를 제공할 수 있다면 좋을 것 같아요..!
