### ISSUE TITLE
[FE] 어드민 동전 줍기 통계 축 값 수정

### ISSUE THREAD

**Issue by chyo1** [innovationacademy-kr/Cabi#1634]
### 작업 설명

<img width="424" alt="스크린샷 2024-06-13 오후 4 37 21" src="https://github.com/innovationacademy-kr/Cabi/assets/142678241/4b315786-b5fd-4501-ad89-62a2f6ca9d47">

어드민 동전 줍기 통계 축 값 수정 부탁드립니다.

### 접근 방법

 y축 값을 0-5회, 5-10회...의 방식으로 표현하면 통계 값을 확인하기에 더 편할 것 같습니다.

**Comment by jnkeniaem** [comment]
앗 이슈 파놓으셨군요..! 회의록에 작성하신 줄 알았습니다. fe/dev/refact_coin#1629 프론트 재화 리팩토링 브랜치에 해당 사항 반영해놓았습니다.
해결 됐으니 이슈 닫겠습니다 !
